name: Buld Go Release Binaries

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      # Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # Build the binaries
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o Websitetool-linux-amd64 main.go
          GOOS=darwin GOARCH=amd64 go build -o Websitetool-darwin-amd64 main.go
          GOOS=windows GOARCH=amd64 go build -o Websitetool-windows-amd64.exe main.go
