name: Generate Release Notes

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o Websitetool-linux-amd64 main.go
          GOOS=darwin GOARCH=amd64 go build -o Websitetool-darwin-amd64 main.go
          GOOS=windows GOARCH=amd64 go build -o Websitetool-windows-amd64.exe main.go

      - name: Create tag
        id: create_tag
        uses: actions/create-release@v1.0.1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: Automated release created by GitHub Actions
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_tag.outputs.upload_url }}
          asset_path: ./Websitetool-linux-amd64
          asset_name: Websitetool-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_tag.outputs.upload_url }}
          asset_path: ./Websitetool-darwin-amd64
          asset_name: Websitetool-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_tag.outputs.upload_url }}
          asset_path: ./Websitetool-windows-amd64.exe
          asset_name: Websitetool-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Generate release notes
        uses: release-drafter/release-drafter@v5.21.1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          config-path: .github/release-drafter.yml

      - name: Create release
        uses: actions/create-release@v1.0.1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.release_notes.outputs.changes }}
          draft: false
          prerelease: false
