name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          # Build and test your project here
          go build -v ./...
          go test -v ./...

      - name: Bump version and create release
        id: create_release
        uses: ncipollo/release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ env.VERSION }}
          title: Release ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          prerelease: false
          
      - name: Update release number
        run: |
          OLD_TAG=$(git tag | tail -n 1)
          NEW_TAG=$(echo $OLD_TAG | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          git tag $NEW_TAG
          git push origin $NEW_TAG
        if: always()
      - name: Update release notes
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update release notes for ${{ env.VERSION }}
          title: Update release notes for ${{ env.VERSION }}
          labels: automated
          branch: release-notes/${{ env.VERSION }}
          base: main
          body: |
            ## Changes
            List your changes here.

            ## Instructions
            Describe how to install and use your project here.
