name: Go Release Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0)"

      - name: Determine next version
        id: next_version
        uses: anothrNick/github-tag-action@v1.18
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          tag_name: v${{ steps.get_tag.outputs.tag }}
          version_prefix: v
          tag_prefix: v

      - name: Build and release
        id: build_release
        uses: wangyoucao577/go-release-action@v1.35
        with:
          tag: ${{ steps.next_version.outputs.tag }}
          title: Release ${{ steps.next_version.outputs.tag }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
