name: Go Release Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0)"

      - name: Bump version
        id: version
        uses: bahmutov/auto-semantic-version@v1
        with:
          current_tag: ${{ steps.get_tag.outputs.tag }}
          commit_message: This is an automated release!
          chore(release): v${{ steps.next_version.outputs.version }}
          prerelease_prefix: rc

      - name: Build and release
        id: build_release
        uses: wangyoucao577/go-release-action@v1.35
        with:
          tag: ${{ steps.version.outputs.version }}
          title: Release ${{ steps.version.outputs.version }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
