name: Go Release Binaries

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    # Check out the code
    - name: Check out code
      uses: actions/checkout@v2

    # Build the binaries
    - name: Build binaries
      run: |
        go build -o myapp main.go

    # Create a tag for the release
    - name: Create tag
      id: create_tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: This is the first release of myapp

    # Upload the binaries as release assets
    - name: Upload release assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_tag.outputs.upload_url }}
        asset_path: ./myapp
        asset_name: myapp
        asset_content_type: application/octet-stream
