name: Generate Release Notes

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - name: Generate release notes
        id: release_notes
        uses: release-drafter/release-drafter@v5.23.0
        env:
          GITHUB_TOKEN: ${{ secrets.GrapheQL }}
        with:
          config-name: release-drafter.yml
          tag: ${{ vars.VERSION }}
          version: ${{ vars.VERSION }}
          prerelease: ${{ vars.PRERELEASE }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.16

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o Websitetool-linux-amd64 main.go
          GOOS=darwin GOARCH=amd64 go build -o Websitetool-darwin-amd64 main.go
          GOOS=windows GOARCH=amd64 go build -o Websitetool-windows-amd64.exe main.go

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_notes.outputs.upload_url }}
          asset_path: ./Websitetool-linux-amd64
          asset_name: Websitetool-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_notes.outputs.upload_url }}
          asset_path: ./Websitetool-darwin-amd64
          asset_name: Websitetool-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_notes.outputs.upload_url }}
          asset_path: ./Websitetool-windows-amd64.exe
          asset_name: Websitetool-windows-amd64.exe
          asset_content_type: application/octet-stream
