name: Update Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        #run: |
        # VERSION=$(grep -oP 'v\d+\.\d+\.\K\d+' <<< $VERSION)
        # VERSION=$((VERSION + 1))
        # NEW_VERSION="v${{ env.VERSION }}"
        # echo "New version: $NEW_VERSION"
        # echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
        env:
          Test: 'Hallo ich bin dumm'
        run: echo ${{ vars.VERSION }}
